### ISSUE TITLE
你好，对不起伸手了，能出个使用Python2,32位版本的CTP版本为6.3.11的vnpy-ctp-wrapper吗

### ISSUE THREAD

**Issue by buermen** [mysl/vnpy-ctp-wrapper#1]
我用的是比较老版本的vnpy，最近期货公司通知我说必须用穿透式监管的api了，vnpy2.01版本虽然有更新api，但是感觉问题还很多，不适用于实盘用，我还是想继续使用的我的版本，我是从编程0基础开始接触vnpy的，写写策略自己加一些小功能还行，底层的东西就无从下手，能麻烦你写个Python2,32位，ctp6.3.11的vnpy-ctp-wrapper吗

I used the older version of vnpy. Recently, the futures company informed me that it is necessary to use the api of the penetrating supervision. Although the vnpy2.01 version has the update API, it still feels that there are still many problems. It is not suitable for actual production. I am from Programming 0 basics began to contact vnpy, write strategy to add some small features, the bottom of the things can not start, can you trouble you to write a Python2, 32-bit, ctp6.3.11 vnpy-ctp-wrapper?

**Comment by mysl** [comment]
穿透式监管不是需要6.3.15吗？ 6.3.11也不行吧

**Comment by buermen** [comment]
> 穿透式监管不是需要6.3.15吗？ 6.3.11也不行吧
是的TAT，我都编译出来了才发现。。请问呆佬你现在在用什么版本的ctp呢

**Comment by mysl** [comment]
我还是6.3.11没升级,  因为好一段时间没有实盘用了。

**Comment by buermen** [comment]
> 我还是6.3.11没升级, 因为好一段时间没有实盘用了。

好的好的，谢谢回复，请问如果你升级ctp的话，这个wrapper会更新吗，或者能推荐个基础向的pybind教程给我吗，我看到现在的vnpy ctp是用pybind编译的，网上搜了教程，都没看到有什么对小白友好的教程

**Comment by buermen** [comment]
> 我还是6.3.11没升级, 因为好一段时间没有实盘用了。

等等，哇，终于看到有上实盘的人了，从我第一天知道vnpy你是第一个我遇见的vnpy上实盘的人能方便留个联系方式交流交流吗，

**Comment by mysl** [comment]
我没有用vnpy，这个wrapper相当于只是一个ctp api的python 封装而已。

**Comment by mysl** [comment]
> 好的好的，谢谢回复，请问如果你升级ctp的话，这个wrapper会更新吗，或者能推荐个基础向的pybind教程给我吗，我看到现在的vnpy ctp是用pybind编译的，网上搜了教程，都没看到有什么对小白友好的教程

也许会直接用vnpy2.0编译出来的binary, 毕竟当时我是为了用一个64位的CTP API python封装。pybind我没有用过，但是你根据vnpy照葫芦画瓢应该不难

**Comment by buermen** [comment]
> > 好的好的，谢谢回复，请问如果你升级ctp的话，这个wrapper会更新吗，或者能推荐个基础向的pybind教程给我吗，我看到现在的vnpy ctp是用pybind编译的，网上搜了教程，都没看到有什么对小白友好的教程
> 
> 也许会直接用vnpy2.0编译出来的binary, 毕竟当时我是为了用一个64位的CTP API python封装。pybind我没有用过，但是你根据vnpy照葫芦画瓢应该不难

奥好的，谢谢，我刚刚鼓捣了半天，没搞出来，主要他现在不像以前一样到处都是文档，我再想想其他办法
